apiVersion: v1
kind: Service
metadata:
  name: notes-app-service
  namespace: nginx
spec:
  selector:
    app: note-app
  ports:
    - protocol: TCP
      port: 80        # external service port
      targetPort: 8000 # matches containerPort in deployment
  type: NodePort       # change to LoadBalancer if on cloud


