apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          # Requests are the guaranteed minimum resources
          # Kubernetes will reserve for this container.
          requests:
            cpu: 100m       # 100 millicores = 0.1 CPU core
            memory: 128Mi   # 128 MiB of RAM

          # Limits are the maximum resources this container
          # is allowed to consume before being throttled/terminated.
          limits:
            cpu: 200m       # 200 millicores = 0.2 CPU core
            memory: 256Mi   # 256 MiB of RAM

        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: my-volume
      volumes:
      - name: my-volume
        persistentVolumeClaim:
          claimName: local-pvc


  #Resource Quotas 
  # resources minimum 
  #        request:
  #         cpu: 100m
  #         memory: 128Mi
  #       limits:
  #         cpu: 200m
  #         memory: 256

