apiVersion: v1
kind: Service
metadata:
  name: apache-service
  namespace: apache
spec:
  selector:
    labels:
    app: apache
  ports:
    - protocol: TCP
      port: 80        # service port
      targetPort: 80  # containerPort from your pod
  type: ClusterIP


